backend:
  name: git-gateway
  branch: master
media_library:
  name: cloudinary
  config:
    cloud_name: dibrkdu2g
    api_key: 985438312242657
    output_filename_only: false
    default_transformations:
      - fetch_format: auto
      - width: 1280
      - quality: auto
      - crop: lpad
media_folder: "static/media"
public_folder: "/media"

# Uncomment to leverage Netlify CMS UI authoring flow
# see: https://www.netlifycms.org/docs/configuration-options/#publish-mode
# publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Posts"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "posts/{{fields.slug}}"
    fields:
      - {label: "Template", name: "template", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - name: featuredImage
        label: Featured image
        widget: object
        fields:
          - {name: src, label: Image, widget: image}
          - {name: alt, label: Alt text, widget: string}
          - {name: title, label: Title, widget: string}
          - {name: id, label: ID, widget: string}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Category", name: "category", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template", name: "template", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Slug", name: "slug", widget: "string"}
      - {label: "Draft", name: "draft", widget: "boolean", default: true}
      - {label: "Body", name: "body", widget: "markdown"}